fix error

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,71 +1,71 @@
 version: 2.1
 
 # commands:
-  destroy-environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    parameters:
-      # Add parameter here   
-    steps:
-      - run:
-          name: Destroy environments
-          when: on_fail
-          command: |
-            # Your code here
-            exit 1
+#   destroy-environment:
+#     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+#     parameters:
+#       # Add parameter here
+#     steps:
+#       - run:
+#           name: Destroy environments
+#           when: on_fail
+#           command: |
+#             # Your code here
+#             exit 1
 
-  revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
-    parameters:
-      # Add parameter here     
-    steps:
-      - run:
-          name: Revert migrations
-          # Add when this will run
-          command: |
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
-            if(( $SUCCESS==1 )); 
-            then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
-            fi
-            
+#   revert-migrations:
+#     description: Revert the last migration if successfully run in the current workflow.
+#     parameters:
+#       # Add parameter here
+#     steps:
+#       - run:
+#           name: Revert migrations
+#           # Add when this will run
+#           command: |
+#             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+#             SUCCESS = 1
+#             if(( $SUCCESS==1 ));
+#             then
+#             #  cd ~/project/backend
+#             #  npm install
+#             #  Add revert code here. You can find this in the Getting Started section.
+#               exit 1
+#             fi
+
 jobs:
-  build-frontend:
-    docker:
-      - image: cimg/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [frontend-deps]
-      - run:
-          name: Build front-end
-          command: |
-            cd frontend
-            npm install
-            npm run build
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: frontend-deps
+    build-frontend:
+        docker:
+            - image: cimg/node:13.8.0
+        steps:
+            - checkout
+            - restore_cache:
+                  keys: [frontend-deps]
+            - run:
+                  name: Build front-end
+                  command: |
+                      cd frontend
+                      npm install
+                      npm run build
+            - save_cache:
+                  paths: [frontend/node_modules]
+                  key: frontend-deps
 
-  build-backend:
-    docker:
-      - image: cimg/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-deps]
-      - run:
-          name: Back-end build
-          command: |
-            cd backend
-            npm install
-            npm run build
-      - save_cache:
-          paths: [backend/node_modules]
-          key: backend-deps
+    build-backend:
+        docker:
+            - image: cimg/node:13.8.0
+        steps:
+            - checkout
+            - restore_cache:
+                  keys: [backend-deps]
+            - run:
+                  name: Back-end build
+                  command: |
+                      cd backend
+                      npm install
+                      npm run build
+            - save_cache:
+                  paths: [backend/node_modules]
+                  key: backend-deps
 
 #   test-frontend:
 #     docker:
@@ -74,7 +74,7 @@ jobs:
 #       # Checkout code from git
 #       # Restore from cache
 #       # Your job code here
-                
+
 #   test-backend:
 #     docker:
 #       # Docker image here
@@ -82,7 +82,7 @@ jobs:
 #       # Checkout code from git
 #       # Restore from cache
 #       # Your job code here
-            
+
 #   scan-frontend:
 #     docker:
 #       # Docker image here
@@ -111,7 +111,7 @@ jobs:
 #               --template-file .circleci/files/backend.yml \
 #               #--tags project=your-tag \
 #               # --stack-name "your back-end stack name with workflow id" \
-#               # --parameter-overrides ID="your workflow id"  
+#               # --parameter-overrides ID="your workflow id"
 #               exit 1
 #       - run:
 #           name: Ensure front-end infrastructure exist
@@ -120,7 +120,7 @@ jobs:
 #               --template-file .circleci/files/frontend.yml \
 #               #--tags project=your-tag \
 #               # --stack-name "your front-end stack name with workflow id" \
-#               # --parameter-overrides ID="your workflow id"  
+#               # --parameter-overrides ID="your workflow id"
 #               exit 1
 #       - run:
 #           name: Add back-end ip to ansible inventory
@@ -131,7 +131,7 @@ jobs:
 #           root: ~/
 #           paths:
 #             - project/.circleci/ansible/inventory.txt
-#       # Here's where you will add some code to rollback on failure      
+#       # Here's where you will add some code to rollback on failure
 
 #   configure-infrastructure:
 #     docker:
@@ -150,7 +150,7 @@ jobs:
 #           command: |
 #             # Your code here
 #             exit 1
-#       # Here's where you will add some code to rollback on failure      
+#       # Here's where you will add some code to rollback on failure
 
 #   run-migrations:
 #     docker:
@@ -167,7 +167,7 @@ jobs:
 #           command: |
 #             # Your code here
 #             exit 1
-#      # Here's where you will add some code to rollback on failure      
+#      # Here's where you will add some code to rollback on failure
 
 #   deploy-frontend:
 #     docker:
@@ -188,8 +188,8 @@ jobs:
 #           name: Deploy frontend objects
 #           command: |
 #             # your code here
-#       # Here's where you will add some code to rollback on failure      
-                    
+#       # Here's where you will add some code to rollback on failure
+
 #   deploy-backend:
 #     docker:
 #       # Docker image here that supports Ansible
@@ -205,11 +205,11 @@ jobs:
 #           name: Deploy backend
 #           command: |
 #             # your code here
-#       # Here's where you will add some code to rollback on failure  
+#       # Here's where you will add some code to rollback on failure
 
 #   smoke-test:
 #     docker:
-#       # Lightweight Docker image 
+#       # Lightweight Docker image
 #     steps:
 #       # Checkout code from git
 #       - run:
@@ -228,7 +228,7 @@ jobs:
 #           name: Frontend smoke test.
 #           command: |
 #             # your code here
-#       # Here's where you will add some code to rollback on failure  
+#       # Here's where you will add some code to rollback on failure
 
 #   cloudfront-update:
 #     docker:
@@ -243,7 +243,7 @@ jobs:
 #           name: Update cloudfront distribution
 #           command: |
 #             # your code here
-#       # Here's where you will add some code to rollback on failure  
+#       # Here's where you will add some code to rollback on failure
 
 # cleanup:
 #     docker:
@@ -263,37 +263,36 @@ jobs:
 #             then
 #               # your code here
 #             fi
-            
 
 workflows:
-  default:
-    jobs:
-      - build-frontend
-      - build-backend
-      # - test-frontend:
-      #     requires: [build-frontend]
-      # - test-backend:
-      #     requires: [build-backend]
-      # - scan-backend:
-      #     requires: [build-backend]
-      # - scan-frontend:
-      #     requires: [build-frontend]
-      # - deploy-infrastructure:
-      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      #     filters:
-      #       branches:
-      #         only: [test-feature-branch]
-      # - configure-infrastructure:
-      #     requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
-      # - deploy-frontend:
-      #     requires: [run-migrations]
-      # - deploy-backend:
-      #     requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
-      # - cleanup:
-      #     requires: [cloudfront-update]
+    default:
+        jobs:
+            - build-frontend
+            - build-backend
+            # - test-frontend:
+            #     requires: [build-frontend]
+            # - test-backend:
+            #     requires: [build-backend]
+            # - scan-backend:
+            #     requires: [build-backend]
+            # - scan-frontend:
+            #     requires: [build-frontend]
+            # - deploy-infrastructure:
+            #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+            #     filters:
+            #       branches:
+            #         only: [test-feature-branch]
+            # - configure-infrastructure:
+            #     requires: [deploy-infrastructure]
+            # - run-migrations:
+            #     requires: [configure-infrastructure]
+            # - deploy-frontend:
+            #     requires: [run-migrations]
+            # - deploy-backend:
+            #     requires: [run-migrations]
+            # - smoke-test:
+            #     requires: [deploy-backend, deploy-frontend]
+            # - cloudfront-update:
+            #     requires: [smoke-test]
+            # - cleanup:
+            #     requires: [cloudfront-update]
